import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";
import assert from "node:assert/strict";

import { buildCodexDirectApiPlugin, buildCodexDirectApiSuite } from "../../scripts/lib/codex-relay-build.mjs";

function writeJson(file, value) {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeFile(file, value) {
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, value, "utf8");
}

function writeApiReviewersSource(repoRoot) {
  const sourceRoot = path.join(repoRoot, "plugins", "api-reviewers");
  writeJson(path.join(sourceRoot, ".codex-plugin", "plugin.json"), {
    name: "api-reviewers",
    version: "0.1.0",
    description: "Delegate code reviews to direct API providers from within Codex.",
    author: { name: "seungpyoson" },
    license: "AGPL-3.0-only",
    homepage: "https://github.com/seungpyoson/relay",
    repository: "https://github.com/seungpyoson/relay",
    interface: {},
  });
  writeJson(path.join(sourceRoot, "config", "providers.json"), {
    glm: { display_name: "GLM" },
    deepseek: { display_name: "DeepSeek" },
  });
  writeJson(path.join(sourceRoot, "config", "session-approval.json"), { max_ttl_ms: 60000 });
  writeFile(path.join(sourceRoot, "bin", "api-reviewer"), "#!/usr/bin/env node\n");
  writeFile(path.join(repoRoot, "LICENSE"), "AGPL-3.0-only\n");
}

test("buildCodexDirectApiPlugin regenerates provider docs and license", () => {
  const repoRoot = mkdtempSync(path.join(tmpdir(), "codex-relay-build-"));
  try {
    writeApiReviewersSource(repoRoot);

    const pluginRoot = buildCodexDirectApiPlugin({ provider: "glm", repoRoot });

    for (const relPath of [
      "commands/glm-review.md",
      "commands/glm-adversarial-review.md",
      "commands/glm-custom-review.md",
      "commands/glm-setup.md",
      "skills/glm-review/SKILL.md",
      "skills/glm-adversarial-review/SKILL.md",
      "skills/glm-custom-review/SKILL.md",
      "skills/glm-setup/SKILL.md",
    ]) {
      const file = path.join(pluginRoot, relPath);
      assert.equal(existsSync(file), true, relPath);
      assert.match(readFileSync(file, "utf8"), /GENERATED by scripts\/ci\/sync-external-model-contracts\.mjs/);
    }

    assert.equal(existsSync(path.join(pluginRoot, "LICENSE")), true);
    assert.equal(existsSync(path.join(pluginRoot, "commands", "deepseek-review.md")), false);
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
  }
});

test("buildCodexDirectApiSuite removes stale generated direct API relay plugin directories", () => {
  const repoRoot = mkdtempSync(path.join(tmpdir(), "codex-relay-suite-stale-"));
  try {
    writeApiReviewersSource(repoRoot);
    writeFile(path.join(repoRoot, "plugins", "relay-old-provider", "stale.txt"), "stale\n");

    const pluginRoots = buildCodexDirectApiSuite({ repoRoot }).map((root) => path.basename(root)).sort();

    assert.deepEqual(pluginRoots, ["relay-deepseek", "relay-glm"]);
    assert.equal(existsSync(path.join(repoRoot, "plugins", "relay-old-provider")), false);
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
  }
});
