import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  EXTERNAL_MODEL_CONTRACT_DOC_TARGETS,
  EXTERNAL_MODEL_CONTRACT_VERSION,
  renderExternalModelContractDoc,
} from "../../scripts/lib/external-model-contracts.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

function readRepoFile(relPath) {
  return readFileSync(path.join(REPO_ROOT, relPath), "utf8");
}

function collectPluginContractPaths() {
  const found = [];

  function walk(relDir) {
    for (const entry of readdirSync(path.join(REPO_ROOT, relDir), { withFileTypes: true })) {
      const relPath = `${relDir}/${entry.name}`;
      if (entry.isDirectory()) {
        walk(relPath);
        continue;
      }
      if (
        /^plugins\/[^/]+\/commands\/[^/]+\.md$/.test(relPath)
        || /^plugins\/[^/]+\/skills\/[^/]+\/SKILL\.md$/.test(relPath)
        || /^plugins\/[^/]+\/agents\/[^/]+\.md$/.test(relPath)
      ) {
        found.push(relPath);
      }
    }
  }

  walk("plugins");
  return found.sort();
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function countOccurrences(text, needle) {
  return text.split(needle).length - 1;
}

test("external model contract docs are generated from one shared source", () => {
  assert.equal(EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.length, 75);

  const targetPaths = new Set();
  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS) {
    assert.ok(!targetPaths.has(target.path), `duplicate generated target ${target.path}`);
    targetPaths.add(target.path);

    const actual = readRepoFile(target.path);
    const expected = renderExternalModelContractDoc(target);
    assert.equal(actual, expected, `${target.path} drifted from the shared external-model contract`);
    assert.match(actual, /GENERATED by scripts\/ci\/sync-external-model-contracts\.mjs/);
    assert.match(actual, new RegExp(`EXTERNAL_MODEL_CONTRACT_VERSION=${EXTERNAL_MODEL_CONTRACT_VERSION}`));
  }

  assert.deepEqual(
    [...targetPaths].sort(),
    collectPluginContractPaths(),
    "every plugin command, skill, and agent contract doc must be generated",
  );

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) => item.kind === "command")) {
    const rendered = renderExternalModelContractDoc(target);
    assert.match(rendered, /disable-model-invocation:\s*true/, `${target.path} must disable direct model invocation`);
    assert.match(rendered, /allowed-tools:/, `${target.path} must constrain tools`);
  }
});

test("shared review contracts keep upstream-parity review-only guarantees", () => {
  const reviewDocs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => ["review", "adversarial-review", "custom-review"].includes(target.workflow))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "This is a review-only contract.",
    "Do not fix findings, apply patches, edit files, or start rescue work from a review result.",
    "Preserve the caller's review text verbatim after routing documented flags.",
    "Return the runtime output verbatim; do not summarize or rewrite findings.",
    "If there is no substantive result or structured output, report review blocked / no findings produced.",
    "Render `external_review_launched` as soon as it appears.",
    "Render `external_review` before findings, status prose, or the review result.",
  ]) {
    assert.match(reviewDocs, new RegExp(escapeRegExp(required)));
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.kind === "command" && ["review", "adversarial-review"].includes(item.workflow)
  )) {
    const rendered = renderExternalModelContractDoc(target);
    assert.match(rendered, /disable-model-invocation:\s*true/, `${target.path} must disable direct model invocation`);
    assert.match(rendered, /allowed-tools:/, `${target.path} must constrain tools`);
    assert.match(rendered, /\$ARGUMENTS/, `${target.path} must preserve raw slash-command arguments`);
  }
});

test("shared rescue contracts are write-capable forwarders, separate from review", () => {
  const rescueDocs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => target.workflow === "rescue" || target.path.endsWith("claude-rescue.md"))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "This is a rescue contract, not a review contract.",
    "Rescue may investigate, edit files, and run verification when the user asks for implementation work.",
    "Forward the user's task text after routing documented flags; do not replace it with a new plan.",
    "Return the runtime output verbatim; do not hide failed or incomplete rescue work.",
  ]) {
    assert.match(rescueDocs, new RegExp(escapeRegExp(required)));
  }

  assert.match(rescueDocs, /--background/);
  assert.match(rescueDocs, /--foreground/);
  assert.doesNotMatch(rescueDocs, /api-reviewer\.mjs[\s\S]*--mode\s+rescue/);
});

test("provider-specific external model contracts keep mechanical safety clauses", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");
  const renderedByPath = new Map(
    EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.map((target) => [
      target.path,
      renderExternalModelContractDoc(target),
    ]),
  );

  assert.match(docs, /approval-request[\s\S]*recommended_tool_justification[\s\S]*approval_token\.value/);
  assert.match(docs, /source_content_transmission:\s*"not_sent"/);
  assert.match(docs, /If approval is denied, follow `denial_action` and generate a relay prompt instead/);
  assert.match(docs, /API_REVIEWERS_MAX_PROMPT_CHARS/);
  assert.match(docs, /GROK_WEB_MAX_PROMPT_CHARS/);
  assert.match(docs, /subscription-backed[\s\S]*tunnel[\s\S]*not silently fall back to paid xAI API billing/i);
  assert.match(docs, /grok2api/);
  assert.match(docs, /UV_CACHE_DIR/);
  assert.match(docs, /tunnel_start\.error_code/);
  assert.match(docs, /--max-steps-per-turn N[\s\S]*`N` must be a positive integer/);
  assert.match(docs, /--auth-mode subscription/);
  assert.match(docs, /Do not print raw OAuth tokens, API-key values, session cookies, tunnel API keys, bearer tokens, or raw secret values/);

  for (const relPath of [
    "plugins/claude/skills/claude-rescue/SKILL.md",
    "plugins/claude/skills/claude-delegation/SKILL.md",
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, /run --mode=rescue --auth-mode subscription --foreground --lifecycle-events jsonl/);
    assert.match(rendered, /run --mode=rescue --auth-mode subscription --background/);
  }

  for (const [relPath, pattern] of [
    ["plugins/claude/commands/claude-setup.md", /doctor --auth-mode subscription/],
    ["plugins/claude/skills/claude-review/SKILL.md", /run --mode=review --auth-mode subscription --foreground/],
    ["plugins/claude/skills/claude-setup/SKILL.md", /doctor --auth-mode subscription --cwd/],
    ["plugins/claude/skills/claude-delegation/SKILL.md", /doctor --auth-mode subscription --cwd/],
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, pattern);
  }

  for (const relPath of [
    "plugins/claude/skills/claude-rescue/SKILL.md",
    "plugins/claude/skills/claude-delegation/SKILL.md",
    "plugins/gemini/skills/gemini-rescue/SKILL.md",
    "plugins/gemini/skills/gemini-delegation/SKILL.md",
    "plugins/kimi/skills/kimi-rescue/SKILL.md",
    "plugins/kimi/skills/kimi-delegation/SKILL.md",
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, /run --mode=rescue [^\n`]*--foreground --lifecycle-events jsonl/);
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.family === "companion-delegation"
  )) {
    const rendered = renderExternalModelContractDoc(target);
    assert.equal(
      countOccurrences(rendered, "Render companion JSON directly."),
      1,
      `${target.path} should not duplicate lifecycle rendering prose`,
    );
  }

  const apiDelegation = renderedByPath.get("plugins/api-reviewers/skills/api-reviewers-delegation/SKILL.md");
  assert.ok(apiDelegation, "missing API reviewers delegation target");
  const apiProviders = new Set(
    EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
      .filter((target) => target.family === "api-reviewers")
      .map((target) => target.provider.provider),
  );
  for (const provider of apiProviders) {
    assert.match(apiDelegation, new RegExp(`doctor --provider ${provider}`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode review`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode adversarial-review`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode custom-review`));
  }
});

test("shared lifecycle and result handling contracts are provider-neutral", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => ["setup", "status", "result", "cancel", "result-handling"].includes(target.workflow))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "External Model Result Handling",
    "Do not rerun a job from result rendering.",
    "Cancel is for background jobs only.",
    "Foreground runs are owned by the active terminal; interrupt them with Ctrl+C.",
    "Do not print raw OAuth tokens, API-key values, session cookies, tunnel API keys, bearer tokens, or raw secret values.",
    "Credential diagnostics may show key names only.",
  ]) {
    assert.match(docs, new RegExp(escapeRegExp(required)));
  }

  assert.doesNotMatch(docs, /Claude-only result handling/i);
});
