import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  EXTERNAL_MODEL_CONTRACT_DOC_TARGETS,
  EXTERNAL_MODEL_CONTRACT_VERSION,
  renderExternalModelContractDoc,
} from "../../scripts/lib/external-model-contracts.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

function readRepoFile(relPath) {
  return readFileSync(path.join(REPO_ROOT, relPath), "utf8");
}

function collectPluginContractPaths() {
  const found = [];

  function walk(relDir) {
    for (const entry of readdirSync(path.join(REPO_ROOT, relDir), { withFileTypes: true })) {
      const relPath = `${relDir}/${entry.name}`;
      if (entry.isDirectory()) {
        walk(relPath);
        continue;
      }
      if (
        /^plugins\/[^/]+\/commands\/[^/]+\.md$/.test(relPath)
        || /^plugins\/[^/]+\/skills\/[^/]+\/SKILL\.md$/.test(relPath)
        || /^plugins\/[^/]+\/agents\/[^/]+\.md$/.test(relPath)
      ) {
        found.push(relPath);
      }
    }
  }

  walk("plugins");
  return found.sort();
}

function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function countOccurrences(text, needle) {
  return text.split(needle).length - 1;
}

test("Claude/Gemini/Kimi docs route explicit file scopes to custom-review before branch-diff", () => {
  const required = /If concrete files or --scope-paths are already known, do not run branch-diff first; use custom-review with those paths and the original prompt/i;
  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.family === "companion" || item.family === "companion-delegation"
  )) {
    if (!["claude", "gemini", "kimi"].includes(target.provider?.plugin)) continue;
    if (!["review", "adversarial-review", "delegation"].includes(target.workflow)) continue;

    const rendered = renderExternalModelContractDoc(target);
    assert.match(rendered, required, target.path);
    assert.match(rendered, /custom-review/i, target.path);
    assert.match(rendered, /--scope-paths/i, target.path);
  }
});

test("external model contract docs are generated from one shared source", () => {
  assert.equal(EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.length, 75);

  const targetPaths = new Set();
  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS) {
    assert.ok(!targetPaths.has(target.path), `duplicate generated target ${target.path}`);
    targetPaths.add(target.path);

    const actual = readRepoFile(target.path);
    const expected = renderExternalModelContractDoc(target);
    assert.equal(actual, expected, `${target.path} drifted from the shared external-model contract`);
    assert.match(actual, /GENERATED by scripts\/ci\/sync-external-model-contracts\.mjs/);
    assert.match(actual, new RegExp(`EXTERNAL_MODEL_CONTRACT_VERSION=${EXTERNAL_MODEL_CONTRACT_VERSION}`));
  }

  assert.deepEqual(
    [...targetPaths].sort(),
    collectPluginContractPaths(),
    "every plugin command, skill, and agent contract doc must be generated",
  );

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) => item.kind === "command")) {
    const rendered = renderExternalModelContractDoc(target);
    assert.match(rendered, /disable-model-invocation:\s*true/, `${target.path} must disable direct model invocation`);
    assert.match(rendered, /allowed-tools:/, `${target.path} must constrain tools`);
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.family === "api-reviewers" || item.family === "api-reviewers-delegation"
  )) {
    const rendered = renderExternalModelContractDoc(target);
    const apiPluginVersion = JSON.parse(readRepoFile("plugins/api-reviewers/.codex-plugin/plugin.json")).version;
    const escapedVersion = escapeRegExp(apiPluginVersion);
    const globalEntrypoint = new RegExp(
      `node "\\$\\{CODEX_HOME:-\\$HOME/\\.codex\\}/plugins/cache/codex-plugin-multi/api-reviewers/${escapedVersion}/scripts/api-reviewer\\.mjs"`,
    );
    assert.match(
      rendered,
      globalEntrypoint,
      `${target.path} must use the global installed api-reviewer entrypoint`,
    );
    assert.doesNotMatch(
      rendered,
      /node plugins\/api-reviewers\/scripts\/api-reviewer\.mjs/,
      `${target.path} must not require caller cwd to be the codex-plugin-multi repo root`,
    );
    assert.doesNotMatch(
      rendered,
      /node "<plugin-root>\/scripts\/api-reviewer\.mjs"/,
      `${target.path} must not use repo-relative plugin-root api-reviewer script paths`,
    );
    assert.doesNotMatch(
      rendered,
      /Run `api-reviewer\b/,
      `${target.path} must not rely on a bare api-reviewer PATH shim`,
    );
    if (target.kind === "command") {
      assert.match(rendered, /Bash\(node:\*\)/, `${target.path} must allow node for the global api-reviewer entrypoint`);
      assert.doesNotMatch(rendered, /Bash\(api-reviewer:\*\)/, `${target.path} must not allow the removed api-reviewer shim`);
    }
  }
});

test("shared review contracts keep upstream-parity review-only guarantees", () => {
  const reviewDocs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => ["review", "adversarial-review", "custom-review"].includes(target.workflow))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "This is a review-only contract.",
    "Do not fix findings, apply patches, edit files, or start rescue work from a review result.",
    "Preserve the caller's review text verbatim after routing documented flags.",
    "Return the runtime output verbatim; do not summarize or rewrite findings.",
    "If there is no substantive result or structured output, report review blocked / no findings produced.",
    "Render `external_review_launched` as soon as it appears.",
    "`external_review_progress` is a heartbeat for long foreground runs; keep the existing launch card visible and do not render it as a terminal result.",
    "Render `external_review` before findings, status prose, or the review result.",
  ]) {
    assert.match(reviewDocs, new RegExp(escapeRegExp(required)));
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.kind === "command" && ["review", "adversarial-review"].includes(item.workflow)
  )) {
    const rendered = renderExternalModelContractDoc(target);
    assert.match(rendered, /disable-model-invocation:\s*true/, `${target.path} must disable direct model invocation`);
    assert.match(rendered, /allowed-tools:/, `${target.path} must constrain tools`);
    assert.match(rendered, /\$ARGUMENTS/, `${target.path} must preserve raw slash-command arguments`);
  }
});

test("shared rescue contracts are write-capable forwarders, separate from review", () => {
  const rescueDocs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => target.workflow === "rescue" || target.path.endsWith("claude-rescue.md"))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "This is a rescue contract, not a review contract.",
    "Rescue may investigate, edit files, and run verification when the user asks for implementation work.",
    "Forward the user's task text after routing documented flags; do not replace it with a new plan.",
    "Return the runtime output verbatim; do not hide failed or incomplete rescue work.",
  ]) {
    assert.match(rescueDocs, new RegExp(escapeRegExp(required)));
  }

  assert.match(rescueDocs, /--background/);
  assert.match(rescueDocs, /--foreground/);
  assert.doesNotMatch(rescueDocs, /api-reviewer\.mjs[\s\S]*--mode\s+rescue/);
});

test("provider-specific external model contracts keep mechanical safety clauses", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");
  const renderedByPath = new Map(
    EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.map((target) => [
      target.path,
      renderExternalModelContractDoc(target),
    ]),
  );

  assert.match(docs, /approval-request[\s\S]*recommended_tool_justification[\s\S]*approval_token\.value/);
  assert.match(
    docs,
    /If the user has already given explicit current-turn approval for the same provider, mode, source packet, prompt hash, scope resolution, request settings, auth path, billing path, selected route, fallback reason, and approval scope/,
  );
  assert.match(docs, /Any change to that tuple requires fresh human approval before source is sent/);
  assert.match(docs, /source_content_transmission:\s*"not_sent"/);
  assert.match(docs, /If approval is denied, follow `denial_action` and generate a relay prompt instead/);
  assert.match(docs, /API_REVIEWERS_MAX_PROMPT_CHARS/);
  assert.match(docs, /GROK_WEB_MAX_PROMPT_CHARS/);
  assert.match(docs, /subscription-backed Grok CLI[\s\S]*not silently fall back to paid xAI API billing/i);
  assert.match(docs, /--transport auto[\s\S]*CLI-primary fallback mode[\s\S]*pre-source CLI readiness, login, auth-timeout, or model-unavailable failure/i);
  assert.match(docs, /Default CLI and explicit auto mode must not fall back to paid xAI API billing or direct API credentials/i);
  assert.match(docs, /grok2api/);
  assert.match(docs, /UV_CACHE_DIR/);
  assert.match(docs, /tunnel_start\.error_code/);
  assert.match(docs, /--max-steps-per-turn N[\s\S]*`N` must be a positive integer/);
  assert.match(docs, /--auth-mode subscription/);
  assert.match(docs, /Do not print raw OAuth tokens, API-key values, session cookies, tunnel API keys, bearer tokens, or raw secret values/);

  for (const relPath of [
    "plugins/claude/skills/claude-rescue/SKILL.md",
    "plugins/claude/skills/claude-delegation/SKILL.md",
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, /run --mode=rescue --auth-mode subscription --foreground --lifecycle-events markdown/);
    assert.match(rendered, /run --mode=rescue --auth-mode subscription --background/);
  }

  for (const [relPath, pattern] of [
    ["plugins/claude/commands/claude-setup.md", /doctor --auth-mode subscription/],
    ["plugins/claude/skills/claude-review/SKILL.md", /run --mode=review --auth-mode subscription --foreground/],
    ["plugins/claude/skills/claude-setup/SKILL.md", /doctor --auth-mode subscription --cwd/],
    ["plugins/claude/skills/claude-delegation/SKILL.md", /doctor --auth-mode subscription --cwd/],
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, pattern);
  }

  for (const relPath of [
    "plugins/claude/skills/claude-rescue/SKILL.md",
    "plugins/claude/skills/claude-delegation/SKILL.md",
    "plugins/gemini/skills/gemini-rescue/SKILL.md",
    "plugins/gemini/skills/gemini-delegation/SKILL.md",
    "plugins/kimi/skills/kimi-rescue/SKILL.md",
    "plugins/kimi/skills/kimi-delegation/SKILL.md",
  ]) {
    const rendered = renderedByPath.get(relPath);
    assert.ok(rendered, `missing generated target ${relPath}`);
    assert.match(rendered, /run --mode=rescue [^\n`]*--foreground --lifecycle-events markdown/);
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    item.family === "companion-delegation"
  )) {
    const rendered = renderExternalModelContractDoc(target);
    assert.equal(
      countOccurrences(rendered, "Render lifecycle markdown cards directly."),
      1,
      `${target.path} should not duplicate lifecycle rendering prose`,
    );
    assert.match(rendered, /resend_confirmation_required/);
    assert.match(rendered, /--resend-confirmation-approved/);
    assert.match(rendered, /narrow the source packet/);
  }

  for (const target of EXTERNAL_MODEL_CONTRACT_DOC_TARGETS.filter((item) =>
    ["api-reviewers", "grok"].includes(item.family) && item.workflow !== "setup"
  )) {
    const rendered = renderExternalModelContractDoc(target);
    assert.equal(
      countOccurrences(rendered, "Render lifecycle markdown cards directly."),
      1,
      `${target.path} should include lifecycle rendering prose once`,
    );
  }

  assert.match(docs, /--lifecycle-events markdown/);
  assert.doesNotMatch(docs, /--lifecycle-events jsonl/);

  const apiDelegation = renderedByPath.get("plugins/api-reviewers/skills/api-reviewers-delegation/SKILL.md");
  assert.ok(apiDelegation, "missing API reviewers delegation target");
  const apiProviders = new Set(
    EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
      .filter((target) => target.family === "api-reviewers")
      .map((target) => target.provider.provider),
  );
  for (const provider of apiProviders) {
    assert.match(apiDelegation, new RegExp(`doctor --provider ${provider}`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode review`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode adversarial-review`));
    assert.match(apiDelegation, new RegExp(`run --provider ${provider} --mode custom-review`));
  }
});

test("shared lifecycle and result handling contracts are provider-neutral", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .filter((target) => ["setup", "status", "result", "cancel", "result-handling"].includes(target.workflow))
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "External Model Result Handling",
    "Do not rerun a job from result rendering.",
    "Cancel is for background jobs only.",
    "Foreground runs are owned by the active terminal; interrupt them with Ctrl+C.",
    "Do not print raw OAuth tokens, API-key values, session cookies, tunnel API keys, bearer tokens, or raw secret values.",
    "Credential diagnostics may show key names only.",
  ]) {
    assert.match(docs, new RegExp(escapeRegExp(required)));
  }

  assert.doesNotMatch(docs, /Claude-only result handling/i);
});

test("route approval contracts expose approval scope semantics and audit fields", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const required of [
    "`session` approval can be reused only while the full approval tuple is unchanged in the current session.",
    "`once` approval authorizes exactly one matching source send and cannot be replayed.",
    "review_metadata.audit_manifest.selected_route",
    "review_metadata.audit_manifest.fallback_reason",
    "review_metadata.audit_manifest.auth_path",
    "review_metadata.audit_manifest.billing_path",
    "review_metadata.audit_manifest.source_send_approval_required",
    "review_metadata.audit_manifest.source_send_approval_state",
    "review_metadata.audit_manifest.approval_scope",
    "Lifecycle cards should include provider, job, session, run kind, mode, scope, source transmission, source bearing, selected route, fallback reason, auth path, billing path, source-send approval state, approval scope, review quality, status, error code, error message, HTTP status, and suggested action when those fields are present.",
  ]) {
    assert.match(docs, new RegExp(escapeRegExp(required)));
  }
});

test("provider-neutral contracts expose the shared audit and status field inventory", () => {
  const docs = EXTERNAL_MODEL_CONTRACT_DOC_TARGETS
    .map((target) => renderExternalModelContractDoc(target))
    .join("\n");

  for (const field of [
    "selected_route",
    "fallback_reason",
    "approval_scope",
    "auth_path",
    "billing_path",
    "source_bearing",
    "source_send_approval_required",
    "source_send_approval_state",
    "source_content_transmission",
    "review_quality.failed_review_slot",
    "review_quality.semantic_failure_reasons",
    "error_code",
    "suggested_action",
  ]) {
    assert.match(docs, new RegExp(escapeRegExp(field)), `missing shared field ${field}`);
  }
});
